name: Agent Credit System Build and Deploy

on:
  push:
    branches:
      - main
      - master
      - staging
      - demo
    paths:
      - '.infra/docker/Dockerfile.nexi-dashboard'
      - '.infra/docker/Dockerfile.acrm'
      - 'apps/nexi-dashboard/**'
      - 'apps/agent-credit-system/**'
      - 'libs/**'
      - '.github/workflows/build-deploy.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (demo/staging/production)'
        required: true
        default: 'demo'
        type: choice
        options:
          - demo
          - staging
          - production

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      gcp_project: ${{ steps.set-project.outputs.gcp_project }}
      service_name: ${{ steps.set-project.outputs.service_name }}
    steps:
      - name: Determine environment
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "environment=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ] || [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/demo" ]; then
            echo "environment=demo" >> $GITHUB_OUTPUT
          else
            echo "environment=demo" >> $GITHUB_OUTPUT
          fi

      - name: Set GCP project and service name
        id: set-project
        run: |
          environment="${{ steps.set-env.outputs.environment }}"

          if [ "$environment" == "production" ]; then
            echo "gcp_project=flowise-staging" >> $GITHUB_OUTPUT
            echo "service_name=acrm" >> $GITHUB_OUTPUT
          elif [ "$environment" == "staging" ]; then
            echo "gcp_project=flowise-staging" >> $GITHUB_OUTPUT
            echo "service_name=acrm" >> $GITHUB_OUTPUT
          else
            echo "gcp_project=flowise-staging" >> $GITHUB_OUTPUT
            echo "service_name=acrm" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: determine-environment
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-environment.outputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .infra/docker/Dockerfile.nexi-dashboard
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=gcr.io/flowise-staging/nexi-dashboard:latest
          cache-to: type=inline
          tags: |
            gcr.io/flowise-staging/nexi-dashboard:latest
            gcr.io/flowise-staging/nexi-dashboard:${{ github.sha }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: flowise-staging
          install_components: 'gcloud'

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file <(echo '${{ secrets.GCP_SA_KEY }}')
          gcloud config set project flowise-staging

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ needs.determine-environment.outputs.service_name }}
          image: gcr.io/flowise-staging/nexi-dashboard:${{ github.sha }}
          region: asia-southeast1
          flags: --allow-unauthenticated --service-account=github-deployment@flowise-staging.iam.gserviceaccount.com
